// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: response.proto

#include "response.pb.h"
#include "response.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace colly {

static const char* Parser_method_names[] = {
  "/colly.Parser/ParseResponse",
};

std::unique_ptr< Parser::Stub> Parser::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Parser::Stub> stub(new Parser::Stub(channel));
  return stub;
}

Parser::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_ParseResponse_(Parser_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Parser::Stub::ParseResponse(::grpc::ClientContext* context, const ::colly::Response& request, ::colly::Parsed* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ParseResponse_, context, request, response);
}

void Parser::Stub::experimental_async::ParseResponse(::grpc::ClientContext* context, const ::colly::Response* request, ::colly::Parsed* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ParseResponse_, context, request, response, std::move(f));
}

void Parser::Stub::experimental_async::ParseResponse(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::colly::Parsed* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ParseResponse_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::colly::Parsed>* Parser::Stub::AsyncParseResponseRaw(::grpc::ClientContext* context, const ::colly::Response& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::colly::Parsed>::Create(channel_.get(), cq, rpcmethod_ParseResponse_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::colly::Parsed>* Parser::Stub::PrepareAsyncParseResponseRaw(::grpc::ClientContext* context, const ::colly::Response& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::colly::Parsed>::Create(channel_.get(), cq, rpcmethod_ParseResponse_, context, request, false);
}

Parser::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Parser_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Parser::Service, ::colly::Response, ::colly::Parsed>(
          std::mem_fn(&Parser::Service::ParseResponse), this)));
}

Parser::Service::~Service() {
}

::grpc::Status Parser::Service::ParseResponse(::grpc::ServerContext* context, const ::colly::Response* request, ::colly::Parsed* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace colly

