// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: response.proto
#ifndef GRPC_response_2eproto__INCLUDED
#define GRPC_response_2eproto__INCLUDED

#include "response.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace colly {

class Parser final {
 public:
  static constexpr char const* service_full_name() {
    return "colly.Parser";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ParseResponse(::grpc::ClientContext* context, const ::colly::Response& request, ::colly::Parsed* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::colly::Parsed>> AsyncParseResponse(::grpc::ClientContext* context, const ::colly::Response& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::colly::Parsed>>(AsyncParseResponseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::colly::Parsed>> PrepareAsyncParseResponse(::grpc::ClientContext* context, const ::colly::Response& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::colly::Parsed>>(PrepareAsyncParseResponseRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void ParseResponse(::grpc::ClientContext* context, const ::colly::Response* request, ::colly::Parsed* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ParseResponse(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::colly::Parsed* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::colly::Parsed>* AsyncParseResponseRaw(::grpc::ClientContext* context, const ::colly::Response& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::colly::Parsed>* PrepareAsyncParseResponseRaw(::grpc::ClientContext* context, const ::colly::Response& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ParseResponse(::grpc::ClientContext* context, const ::colly::Response& request, ::colly::Parsed* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::colly::Parsed>> AsyncParseResponse(::grpc::ClientContext* context, const ::colly::Response& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::colly::Parsed>>(AsyncParseResponseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::colly::Parsed>> PrepareAsyncParseResponse(::grpc::ClientContext* context, const ::colly::Response& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::colly::Parsed>>(PrepareAsyncParseResponseRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void ParseResponse(::grpc::ClientContext* context, const ::colly::Response* request, ::colly::Parsed* response, std::function<void(::grpc::Status)>) override;
      void ParseResponse(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::colly::Parsed* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::colly::Parsed>* AsyncParseResponseRaw(::grpc::ClientContext* context, const ::colly::Response& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::colly::Parsed>* PrepareAsyncParseResponseRaw(::grpc::ClientContext* context, const ::colly::Response& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ParseResponse_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ParseResponse(::grpc::ServerContext* context, const ::colly::Response* request, ::colly::Parsed* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ParseResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ParseResponse() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ParseResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ParseResponse(::grpc::ServerContext* context, const ::colly::Response* request, ::colly::Parsed* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestParseResponse(::grpc::ServerContext* context, ::colly::Response* request, ::grpc::ServerAsyncResponseWriter< ::colly::Parsed>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ParseResponse<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ParseResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_ParseResponse() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::colly::Response, ::colly::Parsed>(
          [this](::grpc::ServerContext* context,
                 const ::colly::Response* request,
                 ::colly::Parsed* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->ParseResponse(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_ParseResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ParseResponse(::grpc::ServerContext* context, const ::colly::Response* request, ::colly::Parsed* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void ParseResponse(::grpc::ServerContext* context, const ::colly::Response* request, ::colly::Parsed* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_ParseResponse<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ParseResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ParseResponse() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ParseResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ParseResponse(::grpc::ServerContext* context, const ::colly::Response* request, ::colly::Parsed* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ParseResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_ParseResponse() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ParseResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ParseResponse(::grpc::ServerContext* context, const ::colly::Response* request, ::colly::Parsed* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestParseResponse(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ParseResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_ParseResponse() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->ParseResponse(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_ParseResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ParseResponse(::grpc::ServerContext* context, const ::colly::Response* request, ::colly::Parsed* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void ParseResponse(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ParseResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_ParseResponse() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::colly::Response, ::colly::Parsed>(std::bind(&WithStreamedUnaryMethod_ParseResponse<BaseClass>::StreamedParseResponse, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ParseResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ParseResponse(::grpc::ServerContext* context, const ::colly::Response* request, ::colly::Parsed* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedParseResponse(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::colly::Response,::colly::Parsed>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ParseResponse<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ParseResponse<Service > StreamedService;
};

}  // namespace colly


#endif  // GRPC_response_2eproto__INCLUDED
