// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response.proto

package colly

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	StatusCode           int32               `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Body                 []byte              `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	Headers              map[string]*Headers `protobuf:"bytes,5,rep,name=Headers,proto3" json:"Headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Response) GetHeaders() map[string]*Headers {
	if m != nil {
		return m.Headers
	}
	return nil
}

type Headers struct {
	Val                  []string `protobuf:"bytes,1,rep,name=Val,proto3" json:"Val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Headers) Reset()         { *m = Headers{} }
func (m *Headers) String() string { return proto.CompactTextString(m) }
func (*Headers) ProtoMessage()    {}
func (*Headers) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{1}
}

func (m *Headers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Headers.Unmarshal(m, b)
}
func (m *Headers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Headers.Marshal(b, m, deterministic)
}
func (m *Headers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Headers.Merge(m, src)
}
func (m *Headers) XXX_Size() int {
	return xxx_messageInfo_Headers.Size(m)
}
func (m *Headers) XXX_DiscardUnknown() {
	xxx_messageInfo_Headers.DiscardUnknown(m)
}

var xxx_messageInfo_Headers proto.InternalMessageInfo

func (m *Headers) GetVal() []string {
	if m != nil {
		return m.Val
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "colly.Response")
	proto.RegisterMapType((map[string]*Headers)(nil), "colly.Response.HeadersEntry")
	proto.RegisterType((*Headers)(nil), "colly.Headers")
}

func init() { proto.RegisterFile("response.proto", fileDescriptor_0fbc901015fa5021) }

var fileDescriptor_0fbc901015fa5021 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0xce, 0xcf, 0xc9,
	0xa9, 0x54, 0x3a, 0xc4, 0xc8, 0xc5, 0x11, 0x04, 0x95, 0x11, 0x92, 0xe3, 0xe2, 0x0a, 0x2e, 0x49,
	0x2c, 0x29, 0x2d, 0x76, 0xce, 0x4f, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x42, 0x12,
	0x11, 0x12, 0xe2, 0x62, 0x71, 0xca, 0x4f, 0xa9, 0x94, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x09, 0x02,
	0xb3, 0x85, 0xcc, 0xb8, 0xd8, 0x3d, 0x52, 0x13, 0x53, 0x52, 0x8b, 0x8a, 0x25, 0x58, 0x15, 0x98,
	0x35, 0xb8, 0x8d, 0x64, 0xf4, 0xc0, 0x26, 0xeb, 0xc1, 0x4c, 0xd5, 0x83, 0x4a, 0xbb, 0xe6, 0x95,
	0x14, 0x55, 0x06, 0xc1, 0x14, 0x4b, 0x79, 0x71, 0xf1, 0x20, 0x4b, 0x08, 0x09, 0x70, 0x31, 0x67,
	0xa7, 0x56, 0x82, 0x2d, 0xe5, 0x0c, 0x02, 0x31, 0x85, 0x54, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a,
	0x53, 0xc1, 0xd6, 0x71, 0x1b, 0xf1, 0x41, 0xcd, 0x85, 0xea, 0x0a, 0x82, 0x48, 0x5a, 0x31, 0x59,
	0x30, 0x2a, 0x49, 0xc3, 0xdd, 0x00, 0x32, 0x26, 0x2c, 0x31, 0x47, 0x82, 0x51, 0x81, 0x19, 0x64,
	0x4c, 0x58, 0x62, 0x8e, 0x13, 0x7b, 0x14, 0xc4, 0xab, 0x49, 0x6c, 0x60, 0x8f, 0x1b, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x78, 0x18, 0x76, 0xce, 0x0a, 0x01, 0x00, 0x00,
}
